### ISSUE TITLE
分别使用源码部署和docker部署，均遇到问题

### ISSUE THREAD

**Issue by fuxiaoye** [zj1244/beholder_scanner#5]
环境：CentOS7 64位
beholder_web运行时报以下错误：
[2020-11-11 Wednesday 17:37] [INFO] Scheduler started
[2020-11-11 Wednesday 17:37] [DEBUG] Looking for jobs to run
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    app.run(use_reloader=False, threaded=True, port=8000, host='0.0.0.0', debug=True)
  File "/home/fuxiaoye/.local/lib/python2.7/site-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/home/fuxiaoye/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 1012, in run_simple
    inner()
  File "/home/fuxiaoye/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 965, in inner
    fd=fd,
  File "/home/fuxiaoye/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 808, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/fuxiaoye/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 701, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib64/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib64/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
[2020-11-11 Wednesday 17:37] [DEBUG] No jobs; waiting until a job is added

docker部署后同样报错：
docker logs $(docker ps | grep zj1244/beholder_web | awk '{print $1}')
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    scheduler.start()
  File "/usr/local/lib/python2.7/dist-packages/flask_apscheduler/scheduler.py", line 97, in start
    self._scheduler.start(paused=paused)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/background.py", line 33, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 158, in start
    store.start(self, alias)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/mongodb.py", line 57, in start
    self.collection.ensure_index('next_run_time', sparse=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1991, in ensure_index
    self.__create_index(keys, kwargs, session=None)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1847, in __create_index
    with self._socket_for_writes() as sock_info:
  File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 196, in _socket_for_writes
    return self.__database.client._socket_for_writes()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 1085, in _socket_for_writes
    server = self._get_topology().select_server(writable_server_selector)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 224, in select_server
    address))
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 183, in select_servers
    selector, server_timeout, address)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: 192.168.88.133:27017: [Errno 113] No route to host
明天我再试试demo，您看下这是什么问题导致的呢？

**Comment by fuxiaoye** [comment]
永久开放27017端口：
firewall-cmd --zone=public --permanent --add-port=27017/tcp; firewall-cmd --reload

After this configured, problem solved. Thank you for developing such a fascinating program.
